// Hand-picked from Wikimedia Commons (checked with scripts/probe-media.mjs): only free licences
// (public domain, CC0, CC BY, CC BY-SA). Author and licence are read from Commons at runtime and
// shown in the app. A title that disappears from Commons is simply skipped.

/** Nature videos: waterfalls, clouds, sea, mountains, glaciers, northern lights, Earth from space. */
export const NATURE_VIDEOS = [
  'Rheinfall (Rhine Falls).webm',
  'Aerial imagery of fjords and rivers in Arctic Norway.webm',
  'Krimmler Wasserfaelle Waterfall in Austria Biggest from Europe 380m at the top.webm',
  'Rhaeadr Ewynnol, Betws-y-coed - waterfall in Wales.webm',
  'Niagara waterfalls with rainbow 2015.webm',
  'Rapids and Falls of the Youghiogheny at Ohiopyle.webm',
  'Wolken Zeitraffer - Clouds Timelapse 4K HD 24FPS.webm',
  '2018-07-15 Timelapse-nuages-belfort.webm',
  'Rialto Beach Waves 2022.webm',
  'Aerial view of sand beach. Top view sea waves. Drone footage.webm',
  'Aerial views of the Swiss Alps.webm',
  'Flight through the Alps in Switzerland.webm',
  'Epic Alaska Glacier Icebergs 4K Creative Commons.webm',
  'Mount Fuji at sunset (timelapse).webm',
  'Aurora borealis timelapse.webm',
  'Northern Lights in Motion- Timelapse of a Severe G4 Storm in 4K.webm',
  'Europe from Space in 4K.webm',
  'Earth Day 2017 - 4K Earth Views From Space.webm',
  'Ultra High Definition (4K) View of Planet Earth.webm',
  'Dark Skies (Timelapse HD).webm',
  'Forest For the Trees 4K.webm',
  'Blue Mountains, Australia (video).webm',
  'Lake Bled Slovenia - by Yuneec Typhoon Q500 4k.webm',
  'Lost between the Atacama Desert and the Andes.webm',
  'Dune du Pilat 2018.webm',
  'Snowdonia by drone.webm'
]

/** Calm music: piano (Chopin, Debussy, Satie, Schubert, Mozart), strings, calm pieces by Kevin MacLeod. */
export const CALM_MUSIC = [
  'Chopin - Nocturne No. 1 in B-flat minor, Op. 9 No. 1 (Olga Gurevich).flac',
  'Chopin - Nocturne No. 2 in E-flat major, Op. 9 No. 2 (Frank Levy).flac',
  'Chopin - Nocturne No. 3 in B major, Op. 9 No. 3 (Xuan He).flac',
  'Chopin - Nocturne No. 4 in F major, Op. 15 No. 1 (Luke Faulkner).flac',
  'Chopin - Nocturne No. 5 in F-sharp major, Op. 15 No. 2 (Luke Faulkner).flac',
  'Chopin - Nocturne No. 7 in C-sharp minor, Op. 27 No. 1 (Luke Faulkner).flac',
  'Chopin - Nocturne No. 8 in D-flat major, Op. 27 No. 2 (Frank Levy).flac',
  'Chopin - Nocturne No. 9 in B major, Op. 32 No. 1 (Frank Levy).flac',
  'Chopin - Nocturne No. 10 in A-flat major, Op. 32 No. 2 (Olga Gurevich).flac',
  'Chopin - Nocturne No. 15 in F minor, Op. 55 No. 1 (Luke Faulkner).flac',
  'Chopin - Nocturne No. 16 in E-flat major, Op. 55 No. 2 (Xuan He).flac',
  'Chopin - Nocturne No. 17 in B major, Op. 62 No. 1 (Olga Gurevich).flac',
  'Chopin - Nocturne No. 18 in E major, Op. 62 No. 2 (Luke Faulkner).flac',
  'Chopin - Nocturne No. 19 in E minor, Op. 72 No. 1 (Luke Faulkner).flac',
  'Chopin - Nocturne No. 20 in C-sharp minor, B. 49 (Frank Levy).flac',
  'Chopin - Nocturne No. 21 in C minor, B. 108 (Diana Hughes).flac',
  'Satie Gymnopedie No 1 performed by Michael Laucke.flac',
  'Satie Gymnopedie No 2 performed by Michael Laucke.flac',
  'Satie Gymnopedie No 3 performed by Michael Laucke.flac',
  'Clair de lune (Claude Debussy) Suite bergamasque.ogg',
  'Claude Debussy - Première Arabesque - Patrizia Prati.ogg',
  'Claude Debussy - Deuxième Arabesque - Patrizia Prati.ogg',
  'La Cathédrale engloutie - Claude Debussy - performed by Ivan Ilic.ogg',
  "Claude Debussy, Images - 01 Reflets dans l'eau (Marcelle Meyer, 1957).flac",
  'Claude Debussy - Préludes (Livre I) - VIII. La Fille aux cheveux de lin (Marcelle Meyer, 1956).flac',
  'Claude Debussy - Préludes (Livre I) - VI. Des pas sur la neige (Marcelle Meyer, 1956).flac',
  'Claude Debussy - Préludes (Livre II) - I. Brouillards (Marcelle Meyer, 1956).flac',
  "Ludwig van Beethoven - sonata no. 14 in c sharp minor 'moonlight', op. 27 no. 2 - i. adagio sostenuto.ogg",
  "Schubert's Impromptu no. 3 in G-flat major, D.899 - Chiara Bertoglio.ogg",
  "Schubert's Impromptu no. 2 in A-flat major, D.935 - Chiara Bertoglio.ogg",
  'Schubert - Piano Sonata No. 13 in A major, D664 - II. Andante (Paul Pitman).flac',
  'Schubert - Piano Sonata No. 20 in A major, D959 - II. Andantino (Paul Pitman).flac',
  'Mozart - Piano Sonata No. 12 in F Major, K.332 - II. Adagio.ogg',
  'W. A. Mozart - Sonata No. 14 K 457 - II. Adagio.ogg',
  'Bach Cello Suite 1 Prelude (BWV 1007) Played by Chris.ogg',
  'JOHN MICHEL CELLO-BACH AVE MARIA.ogg',
  'Bach-Siloti, Prelude in B minor (J. S. Bach, arranged Siloti), arrangement of Prelude in E minor BWV 855a.ogg',
  'Grieg - Peer Gynt Suite No. 1, Op. 46 - I. Morning Mood (Musopen Symphony).flac',
  'Grieg - Peer Gynt Suite No. 1, Op. 46 - II. The Death of Aase (Musopen Symphony).flac',
  'Kevin MacLeod - Canon in D Major.ogg',
  'Kevin MacLeod - Clean Soul.ogg',
  'Kevin MacLeod - Calmant.ogg',
  'Kevin MacLeod - Dream Culture.ogg',
  'Kevin MacLeod - Inner Light.ogg',
  'Kevin MacLeod - Tranquility.ogg',
  'Kevin MacLeod - Snow Drop.ogg',
  'Kevin MacLeod - Windswept.ogg',
  'Kevin MacLeod - Autumn Day.ogg',
  'Kevin MacLeod - Winter Reflections.ogg',
  'Kevin MacLeod - Relent.ogg',
  'Kevin MacLeod - The Endless.ogg',
  'Kevin MacLeod - Enchanted Journey.ogg',
  'Scott Buckley - The Distant Sun (Monomyth 1).oga',
  'Moby - LA1.mp3',
  'Moby - LA3.mp3'
]
