import { app } from 'electron'
import { promises as fs } from 'fs'
import path from 'path'

export interface SketchMeta {
  id: string
  name: string
  updatedAt: number
  thumb: string | null // small PNG data URL for the page list
}

export interface Sketch extends SketchMeta {
  items: unknown[] // strokes and text blocks, drawn by the renderer
  background: string
}

const dir = (): string => path.join(app.getPath('userData'), 'sketches')

function fileFor(id: string): string {
  // ids are generated by the app; never let one escape the folder
  const safe = id.replace(/[^a-zA-Z0-9_-]/g, '')
  if (!safe) throw new Error('Ungültige Zeichnung')
  return path.join(dir(), `${safe}.json`)
}

export async function listSketches(): Promise<SketchMeta[]> {
  let files: string[] = []
  try {
    files = await fs.readdir(dir())
  } catch {
    return []
  }
  const metas: SketchMeta[] = []
  for (const f of files) {
    if (!f.endsWith('.json')) continue
    try {
      const s: Sketch = JSON.parse(await fs.readFile(path.join(dir(), f), 'utf-8'))
      metas.push({ id: s.id, name: s.name, updatedAt: s.updatedAt, thumb: s.thumb ?? null })
    } catch {
      // skip a broken file instead of hiding every sketch
    }
  }
  return metas.sort((a, b) => b.updatedAt - a.updatedAt)
}

export async function getSketch(id: string): Promise<Sketch | null> {
  try {
    return JSON.parse(await fs.readFile(fileFor(id), 'utf-8'))
  } catch {
    return null
  }
}

export async function saveSketch(sketch: Sketch): Promise<void> {
  await fs.mkdir(dir(), { recursive: true })
  const target = fileFor(sketch.id)
  // write to a temp file first so a crash mid-save never corrupts a drawing
  await fs.writeFile(target + '.tmp', JSON.stringify({ ...sketch, updatedAt: Date.now() }), 'utf-8')
  await fs.rename(target + '.tmp', target)
}

export async function deleteSketch(id: string): Promise<void> {
  await fs.unlink(fileFor(id)).catch(() => undefined)
}
